name: Ci
on:
    push:
        branch: ["**"]

env:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PYTHONUNBUFFERED: "1"
    DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}


jobs:
    lint-type-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: 3.12
            cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .[dev]
        
        - name: Lint and Type check
          run: |
            ruff check .
            mypy app
        
        - name: Unit testing
          run: |
            pytest
        
        - name: Build docker image
          run: |
            docker build -t equal-experts-api-interview:ci .

        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
           username: ${{ env.DOCKER_HUB_USERNAME }}
           password: ${{ env.DOCKER_HUB_TOKEN }}
           logout: false

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ secrets.DOCKER_HUB_USERNAME }}/equal-experts-api-interview

        - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v2
          with:
            subject-name: index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/equal-experts-api-interview
            subject-digest: ${{ steps.push.outputs.digest }}
            push-to-registry: true


